version: "3"

services:

  api:
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: mongo:bionic
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
